{
  "hash": "047a879110be78ed80451554ef79d240",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Binomial Logistic Regression\"\nformat: html\nengine: knitr\neditor: source\neditor_options: \n  chunk_output_type: console\n---\n\n\\vspace{-0.5in}\n\n\n\n## Overview\n\nIn this class, you will fit logistic regression models to binomial count data rather to a binary response variable. To learn the basic idea, we'll consider the cancer data displayed in the table below.\n\n| Median Radius | Benign | Malignant | Total | Proportion Malignant |\n|:--------------|-------:|----------:|------:|---------------------:|\n| 2.5           |    113 |         2 |   115 | 0.017               |\n| 3.5           |    140 |        12 |   152 | 0.079               |\n| 4.0           |     85 |        34 |   119 | 0.286               |\n| 4.5           |     17 |        43 |    60 | 0.717               |\n| 6.5           |      2 |       121 |   123 | 0.984               |\n| Total         |    357 |       212 |   569 |\n\n\nThe data set contains a single predictor variable, `Median Radius`, which is the median radius of the cell nuclei (in micrometers) observed in a biopsy. The response variable is the number of malignant cells (out of the total number of cells observed) for each value of the predictor variable.\n\n## Fitting a binomial logistic regression model\n\nBelow is the output from the `glm()` command to fit a binomial logistic regression model to these data.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Malignant/Total ~ Median.Radius, family = \"binomial\", \n    data = table73, weights = Total)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -11.1359     1.1446  -9.729   <2e-16 ***\nMedian.Radius   2.5729     0.2848   9.035   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 412.9453  on 4  degrees of freedom\nResidual deviance:   8.0215  on 3  degrees of freedom\nAIC: 30.852\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n**Task 1.** Report the fitted logistic regression equation (i.e., the fitted log odds).\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nThe fitted logistic regression equation is:\n\n$$\\hat{\\eta}=\\log\\left(\\frac{\\hat{\\pi}}{1 - \\hat{\\pi}}\\right) = -11.1359 + 2.5729 \\cdot \\text{Median Radius}$$\nwhere $\\hat{\\pi}$ is the estimated probability of malignancy.\n:::\n\n\n**Task 2.** Estimate the probability of malignancy when the radius is 4.5.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nTo estimate the probability of malignancy when the radius is 4.5, we first calculate the linear predictor:\n$$\\hat{\\eta} = -11.1359 + 2.5729 \\cdot 4.5 = 0.44215$$\nNext, we convert the linear predictor to a probability using the logistic function:\n$$\\hat{\\pi} = \\frac{e^{\\hat{\\eta}}}{1 + e^{\\hat{\\eta}}} = \\frac{e^{0.44215}}{1 + e^{0.44215}} \\approx 0.609$$\nThus, the estimated probability of malignancy when the radius is 4.5 is approximately 0.608.\n:::\n\n**Task 3.** Use Wald's test to determine if there is evidence that the probability of malignancy is related to cell radius.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nTo use Wald's test, we look at the coefficient for `Median Radius` in the model summary. \n\n$H_0: \\beta_1 = 0$ vs. $H_a: \\beta_1 \\neq 0$\n\nThe test statistic is calculated as:\n$$z = \\frac{\\hat{\\beta}_1}{SE(\\hat{\\beta}_1)} = \\frac{2.5729}{0.2848} \\approx 9.035$$\n\nThe p-value is found using the standard normal distribution (you should know how to do this). It is very small (less than 0.0001), indicating strong evidence against the null hypothesis. Thus, there is very strong evidence that the probability of malignancy is related to cell radius.\n:::\n\n**Task 4.** Use a drop-in deviance test to determine if there is evidence that the probability of malignancy is related to cell radius.\n\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nThis drop-in-deviance test has the same null and alternative hypotheses as Wald's test.\n\nTo perform a drop-in deviance test, we compare the deviance of the full model (with `Median Radius`) to the deviance of the null model (without any predictors).\n\nThe `Null deviance` given in the model summary is 412.9453, and the `Residual deviance` is 8.0215. The test statistic is:\n$$LRT = \\text{Null deviance} - \\text{Residual deviance} = 412.9453 - 8.0215 = 404.9238$$\nThe p-value can be found using the chi-square distribution with 1 degree of freedom. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pchisq(404.9238, df = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nThis p-value is also very small (less than 0.0001), indicating strong evidence against the null hypothesis. Thus, there is very strong evidence that the probability of malignancy is related to cell radius.\n:::\n\n**Task 5.** Do the two tests agree?\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nYes, both Wald's test and the drop-in deviance test lead to the same conclusion. Both tests provide very strong evidence that the probability of malignancy is related to cell radius.\n\nThis is often the case in practice; both tests will usually lead to the same conclusion. When they conflict, trust the drop-in deviance test.\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}