project:
  type: website
  output-dir: docs
  resources:
        - data/

website:
  title: "Stat 230 - Fall 2025"
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

