{
  "hash": "9a2e5f7bbb1bc81ec2c92838ba0b8833",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference and Multiple Explanatory Variables\"\nsubtitle: \"Logistic regression -- Stat 230\"\nformat: \n  revealjs:\n    chalkboard: \n      buttons: false\neditor: source\n---\n\n\n\n\n## Recap: Framingham heart study\n\n**Goal:** Determine whether participant experienced coronary heart disease (CHD) in 10-year window after their exam\n\n- Y = CHD (0 = no, 1 = yes)\n\n- X = participant's age, sex, total cholesterol, and systolic blood pressure\n\n**Strategy:** model the probability of CHD given these factors\n\n\n\n## Binary logistic regression model\n\nIf $Y$ follows a Bernoulli distribution\n\n$${\\rm E}(Y | X) = \\pi(X)$$\n\nWe link this mean function to the explanatory variables using the logit link\n\n\\begin{align*}\n\\eta &= {\\rm logit}(\\pi(X))\\\\ \n&= \\log \\left( \\dfrac{\\pi(X)}{1 - \\pi(X)} \\right) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\cdots + \\beta_p x_p\n\\end{align*}\n\n\n## Framingham model {.smaller}\n\n$\\log \\left( \\dfrac{\\hat{\\pi}(X)}{1 - \\hat{\\pi}(X)} \\right) = -8.08 + 0.061 {\\tt age} + 0.686{\\tt male} + 0.002 {\\tt totChol} - 0.018 {\\tt sysBP}$\n\n. . .\n\n$\\widehat{\\beta}_2$\n\n- $e^{0.686} = 1.986$\n\n- The odds of having a heart attack in the next ten years are nearly twice as high for males as females, after accounting for age, total cholesterol, and systolic blood pressure.\n\n. . .\n\n$\\widehat{\\beta}_4$\n\n- $e^{-0.018} = 0.9822$\n\n- The odds of having a heart attack in the next ten years decrease by about 1.8% (i.e., a factor of 0.982) for a one-unit increase is systolic blood pressure, after accounting for age, sex, and total cholesterol.\n\n\n\n# Wald-based inference for logistic regression\n\n## Maximum likelihood (ML) estimation {.smaller}\n\nThe coefficients in logistic regression are estimated by finding the $\\widehat{\\beta}_0, \\ldots, \\widehat{\\beta}_p$ that maximize the probability of the observed outcomes\n\n\n\n$$L(\\beta) = P(Y_1 = y_1, \\ldots Y_n = y_n | \\beta, X) = \\prod_{i=1}^{n} \\pi(X)^{y_i} \\Big[ 1 - \\pi(X) \\Big]^{1- y_i}$$\n\n\nwhere\n\n$$\\pi(X) = \\dfrac{e^{\\beta_0 + \\beta_1 X_1 + \\cdots + \\beta_p X_p}}{1 + e^{\\beta_0 + \\beta_1 X_1 + \\cdots + \\beta_p X_p}}$$\n\n\n\n\n## Properties of ML estimators\n\nLarge-sample properties of ML estimators, $\\widehat{\\beta}_i$s <br> (if the model is correct):\n\n1. Essentially unbiased\n\n1. SEs can be computed and are about as small as any other unbiased estimator\n\n1. The sampling distributions for the estimators are approximately normal\n\n\n## Wald test for a coefficient \n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Hypotheses:**\n:::\n\n::: {.column width=\"75%\"}\n::: {.fragment fragment-index=1}\n$H_0: \\beta_i = 0 \\quad$ vs. $\\quad H_a: \\beta_i \\ne 0$\n:::\n:::\n\n::::\n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Test statistic:**\n:::\n\n::: {.column width=\"75%\"}\n::: {.fragment fragment-index=2}\n$z = \\dfrac{\\widehat{\\beta}_i}{SE(\\widehat{\\beta}_i)}$\n:::\n:::\n\n::::\n\n<br>\n\n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Reference distribution:**\n:::\n\n::: {.column width=\"75%\"}\n::: {.fragment fragment-index=3}\n$N(0, 1)$\n:::\n:::\n\n::::\n\n\n\n\n\n<!-- ## Framingham example {.smaller} -->\n\n<!-- Does total cholesterol increase the odds of CHD after accounting for age, sex, and systolic blood pressure? -->\n\n\n\n\n<!-- ::: {.fragment fragment-index=1} -->\n<!-- $H_0: \\beta_3 = 0 \\quad \\text{vs.} \\quad \\beta_3 > 0$ -->\n<!-- ::: -->\n\n<!-- ::: {.fragment fragment-index=2} -->\n<!-- $z = \\dfrac{\\widehat{\\beta}_3 - 0}{{\\rm SE}(\\widehat{\\beta}_3)} = \\dfrac{0.00201 - 0}{0.00102} \\approx 1.98$ -->\n<!-- ::: -->\n\n<!-- ::::: {.fragment fragment-index=3} -->\n<!-- :::: {.columns} -->\n<!-- ::: {.column width=\"35%\"} -->\n<!-- ```{r} -->\n<!-- 1 - pnorm(1.98) -->\n<!-- ``` -->\n<!-- ::: -->\n<!-- :::: -->\n<!-- ::::: -->\n\n\n<!-- ::: {.fragment fragment-index=4} -->\n<!-- There is a statistically discernible positive association between the odds of success and total cholesterol, after accounting for age, sex, and systolic blood pressure ($z=1.98$, $p$-value$=0.024$). -->\n<!-- ::: -->\n\n\n## CI for a coefficient \n\nA normal-based confidence interval for ${\\beta}_i$\n\n$$\\widehat{\\beta}_i \\pm z^*_{1-\\alpha/2} SE(\\widehat{\\beta}_i)$$\n\n. . .\n\nCI for the multiplicative effect on odds of success for a 1- unit change in $x$ (odds ratio of Success for $x+1$ vs. $x$):\n\n$$e^{\\widehat{\\beta}_i - z^*_{1-\\alpha/2} SE(\\widehat{\\beta}_i)} \\quad \\text{to} \\quad e^{\\widehat{\\beta}_i + z^*_{1-\\alpha/2} SE(\\widehat{\\beta}_i)}$$\n\n. . .\n\n... for a $C$-unit change in $x$\n\n$$e^{C \\cdot\\widehat{\\beta}_i - z^*_{1-\\alpha/2} C \\cdot SE(\\widehat{\\beta}_i)} \\quad \\text{to} \\quad e^{C \\cdot\\widehat{\\beta}_i + z^*_{1-\\alpha/2} C \\cdot SE(\\widehat{\\beta}_i)}$$\n\n\n## Framingham example\n\n\nWhat impact does age have on the odds of having a heart attack in the next 10 years?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term        estimate std.error    conf.low conf.high\n  <chr>          <dbl>     <dbl>       <dbl>     <dbl>\n1 (Intercept) -8.08      0.412   -8.90        -7.29   \n2 age          0.0610    0.00579  0.0497       0.0724 \n3 male         0.686     0.0930   0.505        0.869  \n4 totChol      0.00201   0.00102  0.00000310   0.00401\n5 sysBP        0.0176    0.00200  0.0137       0.0215 \n```\n\n\n:::\n:::\n\n\n::: {.fragment fragment-index=1}\nLet's construct a 95% confidence interval for $\\beta_1$: $\\quad \\widehat{\\beta}_1 \\pm z^*_{1-\\alpha/2} SE(\\widehat{\\beta}_1)$\n:::\n\n::: {.fragment fragment-index=2}\n$z^*_{1-0.05/2} = z^*_{0.975} =$ 0.975 quantile from $N(0, 1)$ \n:::\n\n::::: {.fragment fragment-index=3}\n:::: {.columns}\n::: {.column width=\"35%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.975)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.959964\n```\n\n\n:::\n:::\n\n:::\n::::\n:::::\n\n::: {.fragment fragment-index=4}\n$0.0610 \\pm 1.96 \\cdot (0.00579) = (0.0497,\\ 0.0724)$\n:::\n\n\n## Framingham example\n\n$0.0610 \\pm 1.96 \\cdot (0.00579) = (0.0497,\\ 0.0724)$\n\n<br>\n\n::: {.fragment fragment-index=1}\nExponentiating the endpoints to get the CI for the odds ratio for a one-year increase in age:\n\n$$e^{0.0497} = 1.051 \\quad \\text{to} \\quad e^{0.0724} = 1.075$$\n:::\n<br>\n\n::: {.fragment fragment-index=2}\nWe are 95% confident that a one-year increase in age is associated with an increase in the odds of having a heart attack in the next 10 year of between 5.1% (a 1.051 factor increase) and  7.5% (a 1.075 factor increase), holding all other variables constant. \n:::\n\n\n## Framingham example\n\n:::{style=\"font-size:0.9em\"}\nHow do the odds of having a heart attack in the next 10 years change for someone 10 years older?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term        estimate std.error    conf.low conf.high\n  <chr>          <dbl>     <dbl>       <dbl>     <dbl>\n1 (Intercept) -8.08      0.412   -8.90        -7.29   \n2 age          0.0610    0.00579  0.0497       0.0724 \n3 male         0.686     0.0930   0.505        0.869  \n4 totChol      0.00201   0.00102  0.00000310   0.00401\n5 sysBP        0.0176    0.00200  0.0137       0.0215 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.fragment fragment-index=1}\n:::{style=\"font-size:0.9em\"}\n95% CI: $\\quad C \\cdot \\left[\\widehat{\\beta}_1 \\pm z^*_{1-\\alpha/2} SE(\\widehat{\\beta}_1)\\right]$\n:::\n:::\n\n\n::: {.fragment fragment-index=2}\n:::{style=\"font-size:0.9em\"}\n$\\begin{split}\n10 \\left[0.0610 \\pm 1.96 \\cdot (0.00579) \\right] &= (10(0.0497),\\ 10(0.0724))\\\\ &= (0.497, \\ 0.724)\\end{split}$\n:::\n:::\n\n::: {.fragment fragment-index=3}\n:::{style=\"font-size:0.9em\"}\nWe are 95% confident that a 10-year increase in age is associated with an increase in the odds of having a heart attack in the next 10 year of between a factor of 1.644 (a 64.4% increase) and  a factor of 2.063 (a 106.3% increase), holding all other variables constant. \n:::\n:::\n\n\n# Likelihood-based inference for logistic regression\n\n## Likelihood function\n\nRecall that the likelihood function gives the plausibility of the observed data given our parameter values\n\n:::{style=\"font-size:0.9em\"}\n$$L(\\beta) = P(Y_1 = y_1, \\ldots Y_n = y_n | \\beta, X) = \\prod_{i=1}^{n} \\pi(X)^{y_i} \\Big[ 1 - \\pi(X) \\Big]^{1- y_i}$$\n:::\n\n. . .\n\n<br>\n\n\n**Idea:**\n\n- \"better\" model explains more of the variation in our data set\n- \"better\" model makes our data more plausible\n\n## Likelihood ratio test {.smaller}\n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Full model:** \n:::\n\n::: {.column width=\"75%\"}\n$\\eta = \\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\cdots + \\beta_k x_k + \\beta_{k+1} x_{k+1} + \\cdots + \\beta_p x_p$\n:::\n::::\n\n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Reduced model: **\n:::\n\n::: {.column width=\"75%\"}\n$\\eta = \\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\cdots + \\beta_k x_k$\n:::\n::::\n\n\n:::::{.fragment fragment-index=1}\n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Hypotheses: **\n:::\n\n::: {.column width=\"75%\"}\n$H_0: \\beta_{k+1} = \\cdots = \\beta_{p} = 0 \\quad \\text{vs.} \\quad H_a:$ at least one $\\beta_j \\ne 0$\n:::\n\n::::\n\n:::::\n\n:::::{.fragment fragment-index=2}\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Test statistic: **\n:::\n::::\n\n\n$$\\text{LRT} = 2 \\cdot \\text{log-likelihood(full model)} - 2 \\cdot  \\text{log-likelihood(reduced model)}$$\n:::::\n\n:::::{.fragment fragment-index=3}\n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Reference distribution:** \n:::\n\n::: {.column width=\"75%\"}\n$\\chi^2$ distribution\n\nd.f. = # $\\beta$s in full model $-$ # $\\beta$s in reduced model\n:::\n\n::::\n:::::\n\n\n\n## Deviance\n\n:::{style=\"font-size:1em\"}\n:::{.callout-note}\n## R implementation\nR reports the **deviance** rather than the log-likelihood\n:::\n:::\n\nIn GLM, deviance is used to measure “unexplained” variation in the response\n\n. . .\n\n<br>\n\nAlternate representation of the LRT test statistic\n\n:::{style=\"font-size:0.8em\"}\n\\begin{align*}\n\\text{LRT} &= 2 \\cdot \\text{log-likelihood(full model)} - 2 \\cdot  \\text{log-likelihood(reduced model)}\\\\\n&= \\text{deviance(reduced model)} - \\text{deviance(full model)}\n\\end{align*}\n:::\n\nThe LRT is sometimes called the drop-in-deviance test\n\n\n## Framingham example {.smaller}\n\nR's default output gives\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept) -8.08      0.412      -19.6  9.65e-86\n2 age          0.0610    0.00579     10.5  5.32e-26\n3 male         0.686     0.0930       7.38 1.56e-13\n4 totChol      0.00201   0.00102      1.98 4.83e- 2\n5 sysBP        0.0176    0.00200      8.80 1.39e-18\n```\n\n\n:::\n:::\n\n\n```\n    Null deviance: 3564.8  on 4189  degrees of freedom\nResidual deviance: 3214.1  on 4185  degrees of freedom\n```\n:::::{.fragment fragment-index=1}\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Full model: **\n:::\n\n::: {.column width=\"75%\"}\n$\\eta = \\beta_0 + \\beta_1 {\\tt age} + \\beta_2 {\\tt male} + \\beta_3 {\\tt totChol} + \\beta_4 {\\tt sysBP}$\n:::\n::::\n\n\n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Reduced model: **\n:::\n\n::: {.column width=\"75%\"}\n$\\eta = \\beta_0$\n:::\n::::\n:::::\n\n:::::{.fragment fragment-index=2}\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Hypotheses: **\n:::\n\n::: {.column width=\"75%\"}\n$H_0: \\beta_1=\\beta_2=\\beta_3=\\beta_4 = 0 \\quad \\text{vs.} \\quad H_a:$ at least one $\\beta_j \\ne 0$\n:::\n\n::::\n:::::\n\n:::::{.fragment fragment-index=3}\n$\\text{LRT} = \\text{deviance(reduced model)} - \\text{deviance(full model)}$\n\n$\\text{LRT} = 3564.8 - 3214.1 = 350.7$\n:::::\n\n:::::{.fragment fragment-index=4}\nd.f. $=5 - 1 = 4$\n:::::\n\n## Framingham example\n\n:::: {.columns}\n::: {.column width=\"25%\"}\n**Hypotheses: **\n:::\n\n::: {.column width=\"75%\"}\n$H_0: \\beta_1=\\beta_2=\\beta_3=\\beta_4 = 0 \\quad \\text{vs.} \\quad H_a:$ at least one $\\beta_j \\ne 0$\n:::\n\n::::\n\n$\\text{LRT} = \\text{deviance(reduced model)} - \\text{deviance(full model)}$\n\n$\\text{LRT} = 3564.8 - 3214.1 = 350.7$\n\nd.f. $=5 - 1 = 4$\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pchisq(350.7, df = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n:::\n::::\n\n:::{.fragment fragment-index=1}\nThere is overwhelming evidence that at least one of the explanatory variables helps explain the odds of having a heart attack in the next ten years ($\\text{LRT}=350.7$, ${\\sf d.f.} = 4$, <br> $p$-value < 0.001).\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}