{
  "hash": "5efb8a6769f2c30b742738448ba3c790",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Quasibinomial Logistic Regression\"\nformat: html\neditor: source\neditor_options: \n  chunk_output_type: console\nexecute:\n  eval: true\n---\n\n\n\n\n## Data overview\n\n*Orobanche* is a genus of parasitic plants without chlorophyll that grow on the roots of flowering plants. In an experiment, seeds from two varieties, Orobanche aegyptiaca 75 and Orobanche aegyptiaca 73, where brushed with extract from either a cucumber root or a bean root. Researchers recorded the number of seeds that eventually germinated.\n\nRun the code chunk below to load the data:\n\n::: {.cell}\n\n```{.r .cell-code}\norobanche <- read.csv(\"https://aloy.github.io/stat230-materials/data/orobanche.csv\")\n```\n:::\n\n\nThe variables in the data set are:\n\n- `y`: count of seeds germinated\n- `n`: number of seeds\n- `variety`: either oa75 or oa73\n- `root`: either cucumber or bean\n\nLast class we fit the following binomial logistic regression model to these data:\n\n$$\n\\text{logit}(\\pi_i) = \\beta_0 + \\beta_1 \\text{variety} + \\beta_2 \\text{root} + \\beta_3 \\text{variety} \\times \\text{root}\n$$\n\nHowever, we found evidence of lack of fit.\n\n## Exploring overdispersion\n\nBelow are the deviance residual plots we created last class. We didn't see clear signs of non-linearity or outliers, so we should explore whether extra-binomial variation (overdispersion) is present.\n\n\n::: {.cell layout-ncol=\"3\"}\n::: {.cell-output-display}\n![](19H-sol-quasibinomial_files/figure-html/unnamed-chunk-3-1.png){width=288}\n:::\n\n::: {.cell-output-display}\n![](19H-sol-quasibinomial_files/figure-html/unnamed-chunk-3-2.png){width=288}\n:::\n\n::: {.cell-output-display}\n![](19H-sol-quasibinomial_files/figure-html/unnamed-chunk-3-3.png){width=288}\n:::\n:::\n\n\n\n**Task 1.** Below is the R output from the `summary()` command. Use it to perform the dd hoc test of overdispersion. What do you conclude?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = y/n ~ variety * root, family = binomial, data = orobanche, \n    weights = n)\n\nCoefficients:\n                         Estimate Std. Error z value Pr(>|z|)  \n(Intercept)               -0.4122     0.1842  -2.238   0.0252 *\nvarietyoa75               -0.1459     0.2232  -0.654   0.5132  \nrootcucumber               0.5401     0.2498   2.162   0.0306 *\nvarietyoa75:rootcucumber   0.7781     0.3064   2.539   0.0111 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 98.719  on 20  degrees of freedom\nResidual deviance: 33.278  on 17  degrees of freedom\nAIC: 117.87\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nTo perform the ad hoc test for overdispersion, we calculate the dispersion parameter, $\\hat{\\psi}$, using the formula:\n$$\n\\hat{\\psi} = \\frac{\\text{Residual deviance}}{\\text{Degrees of Freedom}} = \\frac{33.278}{17} \\approx 1.958\n$$\n\nThis is greater than 1, indicating potential overdispersion.\n:::\n\n\n**Task 2.** Regardless of your answer in Task 1, estimate the dispersion parameter, $\\psi$, and calculate the $\\text{SE}_{quasibinomial}(\\hat{\\beta}_2)$.\n\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nWe have the estimate of the dispersion parameter from Task 1. Now, we can calculate the adjusted standard error for $\\hat{\\beta}_2$ (the coefficient for `root`).\n\n$$\n\\text{SE}_{quasibinomial}(\\hat{\\beta}_2) = \\sqrt{\\hat{\\psi}} \\times \\text{SE}_{binomial}(\\hat{\\beta}_2) = \\sqrt{1.958} \\times 0.2498 \\approx 0.3495\n$$\n:::\n\n**Task 3.** Using this adjusted standard error, conduct a hypothesis test for the null hypothesis that $\\beta_2 = 0$ at the $\\alpha = 0.05$ significance level. (This is for the `root` coefficient.) What do you conclude?\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nUsing the adjusted standard error, we calculate the test statistic: \n\n$$\nt = \\frac{\\hat{\\beta}_2 - 0}{\\text{SE}_{quasibinomial}(\\hat{\\beta}_2)} = \\frac{0.5401 - 0}{0.3495} \\approx 1.545\n$$\n\nTo find the p-value, we use a t-distribution with 17 degrees of freedom:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2 * (1 - pt(1.545, df = 17))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1407576\n```\n\n\n:::\n:::\n\n\nThis gives a p-value of approximately 0.140. We fail to reject the null hypothesis. There is not enough evidence to suggest suggest that there is an association between the root and germination rate after accounting for variety. (Notice that this is a change!)\n\n\n:::\n\n**Task 4.** Construct a 95% confidence interval for $\\beta_2$ using the adjusted standard error. \n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nUsing the adjusted standard error from Task 2, we can construct a 95% confidence interval for $\\beta_2$:\n\n$$\n\\hat{\\beta}_2 \\pm t^*_{17} \\times \\text{SE}_{quasibinomial}(\\hat{\\beta}_2) = 0.5401 \\pm 2.11 \\times 0.3495\n$$\n:::\n\n**Task 5.** The deviance for the model without the interaction term is 39.686 with 18 degrees of freedom. Using this information, conduct a drop-in-deviance test for the interaction term that is adjusted for overdispersion. What do you conclude?\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nThe test statistic for the drop-in-deviance test is calculated as follows:\n\n$$\n\\chi^2 = \\frac{(Deviance_{reduced} - Deviance_{full})/1}{\\hat{\\psi}} = \\frac{39.686 - 33.278}{1.958} \\approx 3.27\n$$\n\nTo find the p-value, we use an F distribution with 1 and 17 degrees of freedom:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pf(3.27, df1 = 1, df2 = 17)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08828123\n```\n\n\n:::\n:::\n\n\nThere is weak evidence of an interaction effect between variety and root.\n:::\n",
    "supporting": [
      "19H-sol-quasibinomial_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}