{
  "hash": "666c80955d96a97a5fc2d9e706813a06",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Binary Logistic Regression\"\nformat: html\nengine: knitr\neditor: source\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n## Overview\n\nIn this activity you will practice how to interpret fitted logistic regression models using a sample from the Framingham Heart Study data set.\n\n slides that the Framingham Heart Study is a long-term study of cardiovascular disease (heart attack, stroke, and other heart problems) that began in 1948. The study identified the idea that body measurements (blood pressure, cholesterol, etc) could predict cardiovascular disease. In this activity we will explore an expanded set of predictor variables to model whether a participant experienced coronary heart disease (CHD) in a 10-year window after their exam. The variables we will consider include:\n \n- `age`: age of participant (in years)\n- `male`: biological sex of participant (1 = male, 0 = female)\n- `totChol`: total cholesterol (mg/dL)\n- `sysBP`: systolic blood pressure (mm Hg)\n\n\n## A \"simple\" logistic regression model\n\nLike in linear regression, we refer to a \"simple\" logistic regression model as one with a single predictor variable. Below is the output from fitting a simple logistic regression model with `totChol` as the predictor variable.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept) -2.89     0.230       -12.6  1.92e-36\n2 totChol      0.00488  0.000926      5.27 1.38e- 7\n```\n\n\n:::\n:::\n\n\n**Task 1.** Interpret the coefficient for `totChol` in the context of this problem. In particular, explain what this coefficient tells us about the relationship between total cholesterol and the odds of experiencing coronary heart disease in a 10-year window.\n\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nThe coefficient for `totChol` is approximately 0.00488. This means that for each additional 1 mg/dL increase in total cholesterol, the log odds of experiencing coronary heart disease in a 10-year window increases by about 0.00488, holding all other variables constant. \n\nBut... we don't think on the log-odds scale, so we convert that to an odds ratio by exponentiating the coefficient: $e^{0.00488.} \\approx 1.005$.\n\nA 1 mg/dL increase in total cholesterol is associated with an approximate 0.5% increase in the odds of experiencing coronary heart disease in a 10-year window.\n:::\n\n\n**Task 2.** Using the model output above, calculate the predicted probability of experiencing coronary heart disease in a 10-year window for participants with the following total cholesterol levels:\n\na. 240 mg/dL\nb. 250 mg/dL\nc. 210 mg/dL\nd. 220 md/dL\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nTo calculate the predicted probability, we first need to calculate the log odds using the fitted logistic regression equation:\n$$\\log \\left( \\dfrac{\\widehat{\\pi}}{1-\\widehat{\\pi}} \\right) = -2.89 + 0.00488 \\times \\text{totChol}$$ \nThen, we convert the log odds to a predicted probability using the formula:\n$$\\widehat{\\pi} = \\dfrac{e^{\\text{log odds}}}{1 + e^{\\text{log odds}}}$$\n\na. For `totChol` = 240 mg/dL:\n- Log odds: $-2.89 + 0.00488 \\times 240 \\approx -1.7188$\n- Predicted probability: $\\dfrac{e^{-1.7188}}{1 + e^{-1.7188}} \\approx 0.152$\nb. For `totChol` = 250 mg/dL:\n- Log odds: $-2.89 + 0.00488 \\times 250 \\approx -1.67$\n- Predicted probability: $\\dfrac{e^{-1.67}}{1 + e^{-1.67}} \\approx 0.158$\nc. For `totChol` = 210 mg/dL:\n- Log odds: $-2.89 + 0.00488 \\times 210 \\approx -1.8652$\n- Predicted probability: $\\dfrac{e^{-1.8652}}{1 + e^{-1.8652}} \\approx 0.134$\nd. For `totChol` = 220 mg/dL:\n- Log odds: $-2.89 + 0.00488 \\times 220 \\approx -1.8164$\n- Predicted probability: $\\dfrac{e^{-1.8164}}{1 + e^{-1.8164}} \\approx 0.139$\n:::\n\n\n**Task 3.** Based on your calculations above, is the effect of a 10 mg/dL increase in total cholesterol on the predicted probability of experiencing coronary heart disease in a 10-year window constant?\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nNo, the effect of a 10 mg/dL increase in total cholesterol on the predicted probability is not constant.\nFrom 240 to 250 mg/dL, the predicted probability increases from approximately 0.152 to 0.158, an increase of about 0.006.\nFrom 210 to 220 mg/dL, the predicted probability increases from approximately 0.134 to 0.139, an increase of about 0.005.\nThe increase in predicted probability is slightly larger when moving from 240 to 250 mg/dL compared to moving from 210 to 220 mg/dL.\n:::\n\n**Task 4.** Calculate the log odds ratio for an increase from 240 to 250 mg/dL in total cholesterol. Then, calculate the log odds ratio for an increase from 210 to 220 mg/dL in total cholesterol. Are these log odds ratios the same? \n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nThe log odds ratio for an increase from 240 to 250 mg/dL in total cholesterol is calculated as follows:\n- Log odds at 250 mg/dL: $-2.89 + 0.00488 \\times 250 \\approx -1.67$\n- Log odds at 240 mg/dL: $-2.89 + 0.00488 \\times 240 \\approx -1.7188$\n- Log odds ratio: $-1.67 - (-1.7188) \\approx 0.0488$\n\nThe log odds ratio for an increase from 210 to 220 mg/dL in total cholesterol is calculated as follows:\n- Log odds at 220 mg/dL: $-2.89 + 0.00488 \\times 220 \\approx -1.8164$\n- Log odds at 210 mg/dL: $-2.89 + 0.00488 \\times 210 \\approx -1.8652$\n- Log odds ratio: $-1.8164 - (-1.8652) \\approx 0.0488$\n\nYes, these log odds ratios are the same, both approximately 0.0488. This indicates that the effect of a 10 mg/dL increase in total cholesterol on the log odds of experiencing coronary heart disease in a 10-year window is constant.\n:::\n\n\n## A categorical predictor variable\n\nNext, let's add biological sex as a predictor variable to the model. Below is the output from fitting a logistic regression model with `totChol` and `male` as the predictor variables.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept) -3.28     0.243       -13.5  1.43e-41\n2 totChol      0.00541  0.000945      5.73 1.02e- 8\n3 male         0.538    0.0874        6.16 7.51e-10\n```\n\n\n:::\n:::\n\n\n**Task 5.** Interpret the coefficient for `male` in the context of this problem. In particular, explain what this coefficient tells us about the relationship between biological sex and the odds of experiencing coronary heart disease in a 10-year window, holding total cholesterol constant.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nThe coefficient for `male` is approximately 0.538. The expected log odds of experiencing coronary heart disease in a 10-year window for male participants is about 0.538 higher than that for female participants, holding total cholesterol constant.\n\nOf course, we don't think on the log-odds scale, so we convert that to an odds ratio by exponentiating the coefficient: $e^{0.538} \\approx 1.713$. Thus, the expected odds of experiencing coronary heart disease in a 10-year window for male participants are about 1.713 times higher than for female participants, holding total cholesterol constant.\n:::\n\n**Task 6.** Write the fitted logistic regression equation for both sexes.\n\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nFemales: $\\log \\left( \\dfrac{\\widehat{\\pi}}{1-\\widehat{\\pi}} \\right) = -3.28 + 0.00541 \\times \\text{totChol}$\n\nMales: $\\log \\left( \\dfrac{\\widehat{\\pi}}{1-\\widehat{\\pi}} \\right) = (-3.28 + 0.538) + 0.00541 \\times \\text{totChol}  = -2.742 + 0.00541 \\times \\text{totChol}$\n:::\n\n\n## A multiple logistic regression model\n\nNext, let's consider the full model with all four predictor variables. Below is the output from fitting a multiple logistic regression model with `totChol`, `male`, `age`, and `sysBP` as the predictor variables.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept) -8.08      0.412      -19.6  9.65e-86\n2 totChol      0.00201   0.00102      1.98 4.83e- 2\n3 male         0.686     0.0930       7.38 1.56e-13\n4 age          0.0610    0.00579     10.5  5.32e-26\n5 sysBP        0.0176    0.00200      8.80 1.39e-18\n```\n\n\n:::\n:::\n\n\n**Task 7.** Interpret the coefficient for `age` in the context of this problem. In particular, explain what this coefficient tells us about the relationship between age and the odds of experiencing coronary heart disease in a 10-year window, holding total cholesterol , biological sex, and systolic blood pressure constant.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nThe coefficient for `age` is approximately 0.061. This means that for each additional year increase in age, the log odds of experiencing coronary heart disease in a 10-year window increases by about 0.061, holding total cholesterol, biological sex, and systolic blood pressure constant.\n\nBut... we don't think on the log-odds scale, so we convert that to an odds ratio by exponentiating the coefficient: $e^{0.061} \\approx 1.063$. Thus, a 1 year increase in age is associated with an approximate 6.3% increase in the odds of experiencing coronary heart disease in a 10-year window, holding total cholesterol, biological sex, and systolic blood pressure constant.\n:::\n\n\n**Task 8.** Using the model output above, calculate the predicted probability of experiencing coronary heart disease in a 10-year window for a 55-year old male participant with a total cholesterol level of 240 mg/dL and a systolic blood pressure of 130 mm Hg.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nTo calculate the predicted probability, we first need to calculate the log odds using the fitted logistic regression equation:\n$$\\log \\left( \\dfrac{\\widehat{\\pi}}{1-\\widehat{\\pi}} \\right) = -8.08 + 0.00201 \\imes \\text{totChol} + 0.686 \\times \\text{male} + 0.061 \\times \\text{age} + 0.0176 \\times \\text{sysBP}$$\nThen, we convert the log odds to a predicted probability using the formula:\n$$\\widehat{\\pi} = \\dfrac{e^{\\text{log odds}}}{1 + e^{\\text{log odds}}}$$\nFor a 55-year old male participant with a total cholesterol level of 240 mg/dL and a systolic blood pressure of 130 mm Hg:\n\n- Log odds: $-8.08 + 0.00201 \\times 240 + 0.686 \\times 1 + 0.061 \\times 55 + 0.0176 \\times 130 \\approx -1.2686$\n- Predicted probability: $\\dfrac{e^{-1.2686}}{1 + e^{-1.2686}} \\approx 0.219$\n:::\n\n\n**Task 9.** Using the model output above, calculate the predicted probability of experiencing coronary heart disease in a 10-year window for a 55-year old female participant with a total cholesterol level of 240 mg/dL and a systolic blood pressure of 130 mm Hg.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nFor a 55-year old female participant with a total cholesterol level of 240 mg/dL and a systolic blood pressure of 130 mm Hg:\n\n- Log odds: $-8.08 + 0.00201 \\times 240 + 0.686 \\times 0 + 0.061 \\times 55 + 0.0176 \\times 130 \\approx -1.9546$\n- Predicted probability: $\\dfrac{e^{-1.9546}}{1 + e^{-1.9546}} \\approx 0.124$\n:::\n\n\n\n## An interaction term\n\nFinally, let's consider a model with an interaction term between `totChol` and `male`. Below is the output from fitting a multiple logistic regression model with `totChol`, `male`, `age`, `sysBP`, and the interaction between `totChol` and `male` as the predictor variables.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  term          estimate std.error statistic  p.value\n  <chr>            <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  -7.76       0.457     -17.0   1.25e-64\n2 totChol       0.000373   0.00144     0.259 7.96e- 1\n3 male         -0.124      0.508      -0.244 8.07e- 1\n4 age           0.0624     0.00585    10.7   1.56e-26\n5 sysBP         0.0177     0.00200     8.82  1.11e-18\n6 totChol:male  0.00333    0.00205     1.62  1.05e- 1\n```\n\n\n:::\n:::\n\n\n**Task 10.** Write the fitted logistic regression equation for both sexes.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nFemales: $\\log \\left( \\dfrac{\\widehat{\\pi}}{1-\\widehat{\\pi}} \\right) = -7.76 + 0.000373 \\times \\text{totChol} + 0.0624 \\times \\text{age} + 0.0177 \\times \\text{sysBP}$\n\nMales: $\\log \\left( \\dfrac{\\widehat{\\pi}}{1-\\widehat{\\pi}} \\right) = (-7.76 -0.124) + (0.000373 + 0.00333) \\times \\text{totChol} + 0.0624 \\times \\text{age} + 0.0177 \\times \\text{sysBP}  = -7.884 + 0.0037 \\times \\text{totChol} + 0.0624 \\times \\text{age} + 0.0177 \\times \\text{sysBP}$\n\n:::\n\n## Hypothesis tests for individual regression coefficients\n\nThe regression coefficients from a logistic regression model are approximately normally distributed, so we can use the normal distribution to conduct hypothesis tests for individual regression coefficients. These tests are called Wald tests. \n\n\n**Task 11.** Using the model output from `mod4` above, let's conduct a hypothesis test to determine whether the interaction between `totChol` and `male` is necessary.\n\na. State the null and alternative hypotheses for this test.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nNull hypothesis ($H_0$): The interaction between `totChol` and `male` is not necessary (the coefficient for the interaction term is equal to zero); thus, $\\beta_{5} = 0$.\n\nAlternative hypothesis ($H_a$): The interaction between `totChol` and `male` is necessary (the coefficient for the interaction term is not equal to zero); thus, $\\beta_{5} \\neq 0$.\n:::\n\nb. Calculate the test statistic for this test. Note: this test statistic is provided in the model output above, but you should check that it is calculated just like we did in the linear regression setting.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nThe test statistic for the interaction term `totChol:male` is calculated as follows:\n$$z = \\dfrac{\\hat{\\beta}_{5} - 0}{SE(\\hat{\\beta}_{5})} = \\dfrac{0.00333 - 0}{0.00205} \\approx 1.62$$\n:::\n\nc. Report the p-value for this test (from the summary table).\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nThe p-value for the interaction term `totChol:male` is approximately 0.105.\n:::\n\nd. Sketch a normal distribution and shade in the area corresponding to the p-value for this test.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nTo sketch a normal distribution and shade in the area corresponding to the p-value for this test, we would draw a standard normal distribution curve (mean = 0, standard deviation = 1).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14H-sol-binary-logistic_files/figure-html/unnamed-chunk-6-1.png){width=336}\n:::\n:::\n\n\n\n:::\n\ne. Using a significance level of $\\alpha = 0.05$, what is your conclusion for this test? Interpret your conclusion in the context of this problem.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\nSince the p-value (approximately 0.105) is greater than the significance level of $\\alpha = 0.05$, we fail to reject the null hypothesis. There is not enough evidence to conclude that the interaction between total cholesterol and biological sex is necessary in predicting the odds of experiencing coronary heart disease in a 10-year window.\n:::",
    "supporting": [
      "14H-sol-binary-logistic_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}