{
  "hash": "acdbd01da4fc8a1659fee96855c10863",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference for Logistic Regression\"\nformat: html\nengine: knitr\neditor: source\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n## Overview\n\nIn this activity you will continue exploring logistic regression models for the Framingham Heart Study data set.\n\nRecall that the Framingham Heart Study is a long-term study of cardiovascular disease (heart attack, stroke, and other heart problems) that began in 1948. The study identified the idea that body measurements (blood pressure, cholesterol, etc) could predict cardiovascular disease. In this activity we will explore an expanded set of predictor variables to model whether a participant experienced coronary heart disease (CHD) in a 10-year window after their exam. The variables we will consider include:\n \n- `age`: age of participant (in years)\n- `currentSmoker`: indicator for whether participant is a current smoker (1 = yes, 0 = no)\n- `totChol`: total cholesterol (mg/dL)\n- `sysBP`: systolic blood pressure (mm Hg)\n- `BMI`: body mass index (weight in kg / (height in m)$^2$)\n\n\n## Confidence intervals\n\nSuppose that you have decided to fit a logistic regression model with `age`, `currentSmoker`, `totChol`, `sysBP`, and `BMI` as predictors. Below is the coefficient table from the `glm()` output for this model.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gihyyfneiq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gihyyfneiq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gihyyfneiq thead, #gihyyfneiq tbody, #gihyyfneiq tfoot, #gihyyfneiq tr, #gihyyfneiq td, #gihyyfneiq th {\n  border-style: none;\n}\n\n#gihyyfneiq p {\n  margin: 0;\n  padding: 0;\n}\n\n#gihyyfneiq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gihyyfneiq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gihyyfneiq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gihyyfneiq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gihyyfneiq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gihyyfneiq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gihyyfneiq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gihyyfneiq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gihyyfneiq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gihyyfneiq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gihyyfneiq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gihyyfneiq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gihyyfneiq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gihyyfneiq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gihyyfneiq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihyyfneiq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gihyyfneiq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gihyyfneiq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gihyyfneiq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihyyfneiq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gihyyfneiq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihyyfneiq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gihyyfneiq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihyyfneiq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gihyyfneiq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihyyfneiq .gt_left {\n  text-align: left;\n}\n\n#gihyyfneiq .gt_center {\n  text-align: center;\n}\n\n#gihyyfneiq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gihyyfneiq .gt_font_normal {\n  font-weight: normal;\n}\n\n#gihyyfneiq .gt_font_bold {\n  font-weight: bold;\n}\n\n#gihyyfneiq .gt_font_italic {\n  font-style: italic;\n}\n\n#gihyyfneiq .gt_super {\n  font-size: 65%;\n}\n\n#gihyyfneiq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gihyyfneiq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gihyyfneiq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gihyyfneiq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gihyyfneiq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gihyyfneiq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gihyyfneiq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gihyyfneiq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gihyyfneiq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−8.341</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.475</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−17.579</td>\n<td headers=\"p.value\" class=\"gt_row gt_left\">&lt;0.001</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.066</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.006</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">11.006</td>\n<td headers=\"p.value\" class=\"gt_row gt_left\">&lt;0.001</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">currentSmoker</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.545</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.096</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.704</td>\n<td headers=\"p.value\" class=\"gt_row gt_left\">&lt;0.001</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">totChol</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.001</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.001</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">1.225</td>\n<td headers=\"p.value\" class=\"gt_row gt_left\">0.2</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">sysBP</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.016</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.002</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.635</td>\n<td headers=\"p.value\" class=\"gt_row gt_left\">&lt;0.001</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">BMI</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.017</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.011</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">1.508</td>\n<td headers=\"p.value\" class=\"gt_row gt_left\">0.13</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n**Task 1.** Calculate a 90% confidence interval for the coefficient of `BMI`. \n\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nTo calculate a 90% Wald-based confidence interval for the coefficient of `BMI`, we can use the formula:\n\n$$\\hat{\\beta}_5 \\pm z_{\\alpha/2} \\cdot SE(\\hat{\\beta}_5)$$  \n\nFrom the output table, we have:\n- $\\hat{\\beta}_5 = 0.017$\n- $SE(\\hat{\\beta}_5) = 0.011$\n\nFor a 90% confidence interval, the critical value $z^*_{0.95}$ is the 0.95 quantile from a standard normal distribution. This can be found using the `qnorm()` function in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.644854\n```\n\n\n:::\n:::\n\n\nThus, the confidence interval is:\n\n$$0.017 \\pm 1.645 \\cdot 0.011 = (-0.001095, 0.035095)$$\n\nRemember that **this CI is on the log odds scale**.\n\n\n:::\n\n**Task 2.** Interpret your confidence interval in context. Use a change of 5 kg/m$^2$ in BMI for your interpretation.\n\n:::{.callout-tip collapse=\"true\"}\n### Solution\n\nTo interpret the confidence interval for the coefficient of `BMI` based on a 5-unit change rather than a one-unit change, we can multiply the endpoints of the confidence interval by 5:\n\n$$(5 \\times -0.001095, 5 \\times 0.035095) = (-0.005475,  0.175475)$$\n\nThen, we can exponentiate these values to convert them from the log-odds scale to the odds ratio scale:\n\n$$\\left(e^{-0.005475}, e^{0.175475}\\right) = (0.9945, 1.1918)$$\n\nWe are 90% confident that a 5 kg/m$^2$ increase in BMI is associated with a change in the  odds of experiencing coronary heart disease in a 10-year window by a factor between 0.9945 and 1.1918, holding all other factors constant. Since this interval includes 1, it suggests that there may be no significant effect of BMI on the odds of coronary heart disease at the 90% confidence level.\n\n:::\n\n\n**Task 3.** Calculate a 90% confidence interval for the coefficient of `currentSmoker`. \n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nWe again use the formula for a Wald-based confidence interval:\n\n$$0.545 \\pm 1.645 \\cdot 0.096 = (0.38708, 0.70292)$$\nRemember that **this CI is on the log odds scale**.\n:::\n\n\n\n**Task 4.** Interpret this confidence interval in context.\n\n:::{.callout-tip collapse=\"true\"}\n### Solution\n\nExponentiating the endpoints of the confidence interval gives us:\n\n$$(e^{0.38708}, e^{0.70292}) = (1.4727, 2.0196)$$\nWe are 90% confident that being a current smoker is associated with an increase in the odds of experiencing coronary heart disease in a 10-year window by a factor between 1.4727 and 2.0196 compared to the odds for a non-smoker with the same total cholesterol, systolic blood pressure, and BMI.\n\n\n:::\n\n## Drop-in deviance tests\n\nIf you are \"star gazing\" at the previous output, you may notice that two predictors are statistically significant at the 0.05 level. \n\n\n**Task 5.** Use a drop-in deviance test to determine whether we can drop `totChol` and `BMI` from our logistic regression model. \n\n\na. State the null and alternative hypotheses for this test.\n\n:::{.callout-tip collapse=\"true\"}\n### Solution\n\n$H_0: \\beta_3 = \\beta_5 = 0$ (The coefficients for `totChol` and `BMI` are both zero, meaning they do not contribute to the model.)\n\n$H_a$: At least one of $\\beta_3$ or $\\beta_5$ is not equal to zero\n\n:::\n\n\nb. Calculate the test statistic for this test. Below are snippets from the output from both models, which you need for this calculation.\n\nFull model:\n```\n    Null deviance: 3524.3  on 4171  degrees of freedom\nResidual deviance: 3203.3  on 4166  degrees of freedom\n```\n\n\n\n\nReduced model:\n\n```\n    Null deviance: 3524.3  on 4171  degrees of freedom\nResidual deviance: 3207.1  on 4168  degrees of freedom\n```\n\n:::{.callout-tip collapse=\"true\"}\n### Solution\nThe test statistic for a drop-in deviance test is calculated as the difference in residual deviance between the reduced and full models:\n\n$$\n\\begin{split}\n\\text{LRT} &= \\text{deviance(reduced model)} - \\text{deviance(full model)}\\\\\n&= 3207.1 - 3203.3\\\\\n&= 3.8\n\\end{split}\n$$\n\n:::\n\nc. Calculate the p-value for this test.\n\n:::{.callout-tip}\n## `pchisq()`\nYou can use the `pchisq()` function in R to calculate areas under a chi-square distribution. For example, to calculate the area to the right of 5.99 under a chi-square distribution with 2 degrees of freedom, you would use the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pchisq(5.99, df = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05003663\n```\n\n\n:::\n:::\n\n:::\n\n\n:::{.callout-tip collapse=\"true\"}\n### Solution\nThe degrees of freedom for this test is equal to the difference in the number of predictors between the full and reduced models; thus, df = 2. \n\nThe p-value can be calculated using the chi-square distribution. Specifically, we want to find the the tail area to the right of our test statistic (3.8) with 2 degrees of freedom.\n\nIn R, we can use the `pchisq()` function to calculate this area:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pchisq(3.8, df = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1495686\n```\n\n\n:::\n:::\n\n\nOur p-value is approximately 0.15.\n\n:::\n\n\n\nd. State your conclusion in the context of the problem. You may use a significance level of 0.05.\n\n:::{.callout-tip collapse=\"true\"}\n### Solution\n\nSince our p-value is greater than 0.05, we fail to reject the null hypothesis. There is no evidence to suggest that at least one of the coefficients for `totChol` or `BMI` is not equal to zero. Therefore, we can drop these predictors from our logistic regression model.\n\n:::\n\n\n\n**Task 6.** What model do you think is being described by the `Null deviance` line of the output above? (Hint: think about what \"null\" means in this context, it's similar to our extra-sums-of-squares F-test.)\n\n\n:::{.callout-tip collapse=\"true\"}\n### Solution\n\nThe `Null deviance` corresponds to a model that only includes the intercept (no predictors). This model predicts the same probability of experiencing coronary heart disease for all participants, regardless of their individual characteristics.\n:::\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}