{
  "hash": "ddc4c37a4bd27f3510c49e3e8bd79e63",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference for Prediction in SLR\"\nformat: html\neditor: source\n---\n\n\n\n## Warm-up questions\n\nIs education level associated with income? Researchers collected education level (in years) and income (in thousands of dollars) for a random sample of 32 employees working for the city of Riverview.\n\n\n\nThe researchers fit a simple linear regression of income on education and obtained the following output:\n\n\n::: {.cell tbl-align='center'}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic|p.value |\n|:-----------|--------:|---------:|---------:|:-------|\n|(Intercept) |   11.321|     6.123|     1.849|0.074   |\n|education   |    2.651|     0.370|     7.173|<0.001  |\n\n\n:::\n:::\n\n\n**Q1.** Write the fitted regression equation.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n$\\widehat{y} = 11.3 + 2.65x$\n:::\n\n**Q2.** Interpret the slope coefficient in the context of the problem. (Don't forget to specify units.)\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nFor a one-year increase in education level we expect average income to increase by \\$2,650.\n:::\n\n**Q3.** Interpret the intercept in the context of the problem. (Don't forget to specify units.)\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nFor an employee with 0 years of education, we expect their average income to be \\$11,300. (Note: This interpretation may not make sense in context since it's unlikely that an employee would have 0 years of education.)\n:::\n\nA new researcher joined the team and decided that education should be standardized (to have mean 0 and SD 1) before fitting the regression model. The output from this regression is shown below:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term             | estimate| std.error| statistic|p.value |\n|:----------------|--------:|---------:|---------:|:-------|\n|(Intercept)      |   53.742|     1.587|    33.861|<0.001  |\n|scale(education) |   11.567|     1.613|     7.173|<0.001  |\n\n\n:::\n:::\n\n\n**Q4.** Write the fitted regression equation for this new model.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n$\\widehat{y} = 53.7 + 11.6x$\n:::\n\n**Q5.** Interpret the slope coefficient in the context of the problem. (Don't forget to specify units.)\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nFor a one standard deviation increase in education level we expect average income to increase by \\$11,600.\n:::\n\n**Q6.** Interpret the intercept in the context of the problem. (Don't forget to specify units.)\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nAn employee with average education level (since the standardized value is 0) is expected to have an income of \\$53,700.\n:::\n\n**Q7.** Compare the two models. What's the same? What's different?\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nThe two models have different regression coefficients and standard errors, but they have the same overall association between the explanatory and predictor variable.\n:::\n\n## Prediction and confidence intervals\n\n::: callout-tip\nThe R code for the following questions is found at <br>\n\n<https://aloy.github.io/stat230-materials/activity/04-slr-prediction>.\n\nThe URL is also posted on Moodle.\n:::\n\nFor this activity you will consider predicting the price of a used car (it's Kelly Blue Book value) based on its mileage. The columns of interest in the `Cars` data set are `Price` and `Mileage`.\n\n**Q1.** Use the `lm()` command to fit the simple linear regression model where Mileage is used to predict Price. Report the fitted regression equation.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncars <- read.csv(\"https://aloy.github.io/stat230-materials/data/Cars.csv\")\ncar_mod <- lm(Price ~ Mileage, data = cars)\ncar_mod\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Price ~ Mileage, data = cars)\n\nCoefficients:\n(Intercept)      Mileage  \n 24764.5590      -0.1725  \n```\n\n\n:::\n:::\n\n\n$\\widehat{y} = 24764.56 - 0.17x$\n:::\n\n**Q2.** The first car in the data set is a Buick Century with 8221 miles. Calculate the expected price of this car using the fitted regression equation.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nUsing the regression equation, we have: $$\\widehat{y} = 24764.56 - 0.17(8221) = 23366.99$$ So, the expected price of this car is \\$23,366.99.\n\nIn R, we use `predict()` to find the expected price:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(car_mod, newdata = data.frame(Mileage = 8221))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n23346.27 \n```\n\n\n:::\n:::\n\n\nThe slight difference here is due to rounding in the coefficients for the \"by hand\" calculation.\n:::\n\n**Q3.** If we want to predict the price of **this** car, should we use a confidence interval or a prediction interval?\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nWe should use a prediction interval because we are predicting the price of an individual car, not the average price of cars with that mileage.\n:::\n\n**Q4.** Use R to construct the appropriate 89% interval for the price of this car. Record this interval below.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(car_mod, newdata = data.frame(Mileage = 8221), \n        interval = \"prediction\", level = 0.89)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 23346.27 7654.458 39038.08\n```\n\n\n:::\n:::\n\n:::\n\n**Q5.** Interpret the interval in context.\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nWe are 89% confident that the price of a Buick Century with 8221 miles is between \\$7,654.46 and \\$39,038.08.\n:::\n\n**Q6.** Run the code to produce a scatterplot, regression line, and both types of intervals. Which is the prediction interval and which is the confidence interval? How can you tell?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04H-sol-slr-prediction_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nThe wider interval is the prediction interval, and the narrower interval is the confidence interval. This is because prediction intervals account for both the uncertainty in estimating the mean response and the variability of individual responses around that mean, while confidence intervals only account for the uncertainty in estimating the mean response.\n:::\n",
    "supporting": [
      "04H-sol-slr-prediction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}