{
  "hash": "48edb6d565d7edb870f447b3050e9e63",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Linear Regression\"\nsubtitle: \"Stat 230: Applied Regression Analysis\"\nformat: \n  revealjs:\n    theme: [serif, styles.scss]\n    scrollable: true\neditor: source\neditor_options: \n  chunk_output_type: console\ncode-annotations: hover\n---\n\n\n\n# [PDF version of slides](pdf_slides/07-mlr-intro.pdf)\n\n## Multiple Linear Regression (MLR)\n\n\n\n$$Y_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\cdots + \\beta_p x_{ip} + \\varepsilon_i, \\quad \\varepsilon_i \\overset{iid}{\\sim} N(0, \\sigma^2)$$\n\n<br>\n\n. . .\n\nThis model requires that...\n\n1. $\\mu\\{Y|x_1, x_2, \\ldots, x_p\\}$ is a linear function\n\n2. The error terms are independent and are from a single population distribution\n\n3. The error terms follow a normal distribution with mean 0 and variance $\\sigma^2$\n\n\n\n---\n\n\n## Example\n\n\n- In an effort to understand the\nimportant aspects of a satisfactory supervisor, clerical employees at a large financial organization were asked to rate their immediate supervisor. \n\n- The survey questions were designed to measure overall\nperformance of the supervisor, as well as six additional characteristics. \n\n- Employees were asked to rate the\nfollowing statements on a scale from 0 to 100 \n\n    (0 = \"completely disagree\", 100 = \"completely\nagree\")\n\n---\n\n## The data {.smaller}\n\n\nVariable |\tDescription\n-----        | -------------------\n`rating`     |\tOverall rating of supervisor performance\n`complaints` |\tScore for “Your supervisor handles employee complaints appropriately.”\n`privileges` |\tScore for “Your supervisor allows special privileges.”\n`learn`      |\tScore for “Your supervisor provides opportunities to learn new things.”\n`raises`     |\tScore for “Your supervisor bases raises on performance.”\n`critical`   |\tScore for “Your supervisor is too critical of poor performance.”\n`advance`    |\tScore for “I am not satisfied with the rate I am advancing in the company?”\n\n\n---\n\n## EDA: Scatterplot matrix\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07-mlr-intro_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n---\n\n## EDA: Correlation matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(supervisor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           overall complaints privileges  learn raises critical advance\noverall     1.0000     0.8254     0.4261 0.6237 0.5901   0.1564  0.1551\ncomplaints  0.8254     1.0000     0.5583 0.5967 0.6692   0.1877  0.2246\nprivileges  0.4261     0.5583     1.0000 0.4933 0.4455   0.1472  0.3433\nlearn       0.6237     0.5967     0.4933 1.0000 0.6403   0.1160  0.5316\nraises      0.5901     0.6692     0.4455 0.6403 1.0000   0.3769  0.5742\ncritical    0.1564     0.1877     0.1472 0.1160 0.3769   1.0000  0.2833\nadvance     0.1551     0.2246     0.3433 0.5316 0.5742   0.2833  1.0000\n```\n\n\n:::\n:::\n\n\n\n\n---\n\n## Fitting the model\n\n\n**Target:** \n\n- Fitted regression equation: $\\widehat{Y}_i = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 x_{i1} + \\widehat{\\beta}_2 x_{i2} + \\cdots + \\widehat{\\beta}_p x_{ip}$\n\n- Standard error for MLR model: $\\widehat{\\sigma}$\n\n\n\n---\n\n## Fitting the model\n\n**Procedure:**\n\nLeast squares estimation: choose the coefficients to minimize \n$$\\text{SSE} = \\sum_{i=1}^n \\left(Y_i - \\widehat{Y}_i \\right)^2$$\nThen use $\\widehat{\\sigma} = \\sqrt{\\frac{\\text{SSE}}{n-(p+1)}}$\n\n\n---\n\n## Interpreting $\\widehat{\\beta}_0$ {.incremental}\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  complaints  privileges       learn      raises    critical \n     10.787       0.613      -0.073       0.320       0.082       0.038 \n    advance \n     -0.217 \n```\n\n\n:::\n:::\n\n\n- The expected value of the response variable when all explanatory variables are 0\n\n- The expected overall supervisor score is about 10.8 when all individual scores are 0\n\n\n---\n\n## Interpreting $\\widehat{\\beta}_j$ {.incremental}\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  complaints  privileges       learn      raises    critical \n     10.787       0.613      -0.073       0.320       0.082       0.038 \n    advance \n     -0.217 \n```\n\n\n:::\n:::\n\n\n\n\n- The expected change in the response for a 1-unit increase in $x_j$, when all other variables are held constant.\n\n- We expect a 0.613 point increase in a supervisor's overall score for a 1-point increase on the complaints scale, holding all other variables constant\n\n\n\n---\n\n## Testing a single coefficient\n\n::: {style=\"font-size: 0.9em;\"}\n**Hypotheses:** $H_0: \\ \\beta_j = \\#$ vs. $H_a: \\ \\beta_j \\underset{>}{\\overset{<}{\\ne}} \\#$\n:::\n\n. . .\n\n::: {style=\"font-size: 0.8em;\"}\n**Test statistic:** $t = \\dfrac{\\hat{\\beta}_j - \\#}{SE(\\beta_j)}$\n:::\n\n. . .\n\n::: {style=\"font-size: 0.9em;\"}\n**Reference distribution:** $t$ distribution with d.f. = $n-(p+1)$\n:::\n\n. . .\n\n::: {style=\"font-size: 0.9em;\"}\n**p-value:** Area in the tail(s) specified by $H_a$\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-mlr-intro_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=850}\n:::\n:::\n\n\n\n---\n\n## Confidence intervals \n\n$\\widehat{\\beta}_j \\pm t^*_{n-(p+1)} \\cdot SE(\\widehat{\\beta}_j )$\n\n\n<br>\n\n. . .\n\n\n$t^*_{n-(p+1)}$ is the $1 - \\alpha/2$ quantile from the t-distribution with $d.f. = n-(p+1)$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-mlr-intro_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=528}\n:::\n:::\n\n\n\n\n---\n\n## Example {.smaller}\n\n\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 10.7871 </td>\n   <td style=\"text-align:right;\"> 11.5893 </td>\n   <td style=\"text-align:right;\"> 0.9308 </td>\n   <td style=\"text-align:right;\"> 0.3616 </td>\n   <td style=\"text-align:right;\"> -13.1871 </td>\n   <td style=\"text-align:right;\"> 34.7613 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> complaints </td>\n   <td style=\"text-align:right;\"> 0.6132 </td>\n   <td style=\"text-align:right;\"> 0.1610 </td>\n   <td style=\"text-align:right;\"> 3.8090 </td>\n   <td style=\"text-align:right;\"> 0.0009 </td>\n   <td style=\"text-align:right;\"> 0.2802 </td>\n   <td style=\"text-align:right;\"> 0.9462 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> privileges </td>\n   <td style=\"text-align:right;\"> -0.0731 </td>\n   <td style=\"text-align:right;\"> 0.1357 </td>\n   <td style=\"text-align:right;\"> -0.5382 </td>\n   <td style=\"text-align:right;\"> 0.5956 </td>\n   <td style=\"text-align:right;\"> -0.3538 </td>\n   <td style=\"text-align:right;\"> 0.2077 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> learn </td>\n   <td style=\"text-align:right;\"> 0.3203 </td>\n   <td style=\"text-align:right;\"> 0.1685 </td>\n   <td style=\"text-align:right;\"> 1.9009 </td>\n   <td style=\"text-align:right;\"> 0.0699 </td>\n   <td style=\"text-align:right;\"> -0.0283 </td>\n   <td style=\"text-align:right;\"> 0.6689 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> raises </td>\n   <td style=\"text-align:right;\"> 0.0817 </td>\n   <td style=\"text-align:right;\"> 0.2215 </td>\n   <td style=\"text-align:right;\"> 0.3690 </td>\n   <td style=\"text-align:right;\"> 0.7155 </td>\n   <td style=\"text-align:right;\"> -0.3764 </td>\n   <td style=\"text-align:right;\"> 0.5399 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> critical </td>\n   <td style=\"text-align:right;\"> 0.0384 </td>\n   <td style=\"text-align:right;\"> 0.1470 </td>\n   <td style=\"text-align:right;\"> 0.2611 </td>\n   <td style=\"text-align:right;\"> 0.7963 </td>\n   <td style=\"text-align:right;\"> -0.2657 </td>\n   <td style=\"text-align:right;\"> 0.3425 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> advance </td>\n   <td style=\"text-align:right;\"> -0.2171 </td>\n   <td style=\"text-align:right;\"> 0.1782 </td>\n   <td style=\"text-align:right;\"> -1.2180 </td>\n   <td style=\"text-align:right;\"> 0.2356 </td>\n   <td style=\"text-align:right;\"> -0.5857 </td>\n   <td style=\"text-align:right;\"> 0.1516 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}