---
title: "Polynomial Regression"
webr:
  packages:
    - ggformula
format: 
  live-html:
    toc: true
engine: knitr
editor: source
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}


## Loading data

To load the wildfires data set, run the following code chunk:

```{webr}
# wildfires <- read.csv("https://aloy.github.io/stat230-materials/data/wildfires.csv")
```



## Fitting a polynomial regression model

To fit a polynomial regression model we still use the `lm()` command, but we expand our formula to include polynomial terms. To include polynomial terms in a regression model, we need to use the `I()` function to indicate that we want to calculate a polynonial term. For example, to fit the quadratic model we have already discussed in class, we use the following code:

```{webr}
# quadratic_lm <- lm(Acres ~ I(Year^2), data = wildfires)
```


Use the `lm()` command to fit the simple linear regression
model where Mileage is used to predict Price.

```{webr}
#| min-lines: 3
# Write your lm() command here
```

***

## Function quick reference

The following table summarizes the functions we learned today:

| Function | Purpose |
|----|-----------|
| `lm(formula, data)` | Fit a linear model |
| `predict(model, newdata, interval, level, se.fit)` | Make predictions and | calculate intervals |
| `gf_point(formula, data) |> gf_lm(interval = "confidence")` | Plot data and add confidence intervals for the mean response|
| `gf_point(formula, data) |> gf_lm(interval = "prediction")` | Plot data and add prediction intervals for the mean response|



