---
title: "Regression Cautions"
subtitle: "Be Wary of R<sup>2</sup> when comparing models"
webr:
  packages:
    - Sleuth3
format: 
  live-html:
    toc: true
editor: source
editor_options: 
  chunk_output_type: console
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}


We all love R<sup>2</sup> right? It is "easy" to interpret and is a popular metric of model fit to report in many fields. While I agree that  R<sup>2</sup> is a nice metric for describing a **single** model, it has an issue when it's used to compare models. In this example, you'll explore this issue.

Case Study 10.1.1 in *The Statistical Sleuth* describes Galileo's experiment that led him to discover that the trajectory of a body falling with horizontal velocity is a parabola (see page 272). The `case1011` data set in the `Sleuth3` R package contains the results of Galileo's experiment. The data set contains seven observations on the following two variables: the horizontal distance traveled from the edge of the table to its landing spot, and the initial height of the object. Both measurements are in punti (1 punti = or 169/180 mm or about 0.037 in).

Fit each of the polynomial models specified on your worksheet and record the R<sup>2</sup> value for each in the table on your handout. I've gotten you started with the first-order model below.

```{webr}
mod <- lm(Distance ~ Height, data = case1001)
summary(mod)
```


What do you observe about the R<sup>2</sup> values as you add more polynomial terms to the model? 