---
title: "Binary Logistic Regression in R"
webr:
  packages:
    - Sleuth3
    - broom
format: 
  live-html:
    toc: true
editor: source
editor_options: 
  chunk_output_type: console
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Fitting a Binary Logistic Regression Model

Fitting a binary logistic regression model in R is similar to fitting a linear regression model. To guide you through this process, let's revisit the Framingham Heart Study data set that we discussed in class.

To load the data, run the following code chunk:

```{webr}
framingham <- read.csv("https://aloy.github.io/stat230-materials/data/framingham.csv")
```

Binary logistic regression requires a binary response variable. In this case, we will use the `TenYearCHD` variable, which indicates whether an individual developed coronary heart disease within ten years (1 = yes, 0 = no). Be sure to always check that your response variable is coded correctly before modeling.


Next, we will fit a binary logistic regression model using the `glm()` function in R. The syntax is similar to that of the `lm()` function, but we need to specify the `family` argument as `binomial` to indicate that we are performing logistic regression. Here, we will model the probability of developing coronary heart disease based on age.

```{webr}
logistic_model <- glm(TenYearCHD ~ age, data = framingham, family = binomial)
```

You can still use the `summary()` function to view the results of the model fit:

```{webr}
summary(logistic_model)
```

Much of the regression output looks the same as in linear regression, but there are some key differences. The main differences are:

- The test statistic is no labeled `z value` instead of `t value`.
- A `Null deviance` and `Residual deviance` are reported instead of `Multiple R-squared` and `Adjusted R-squared`.


## Making predictions

We can also use R to calculate the predicted probabilities from our fitted logistic regression model using the `predict()` function. Below is an example where we are calculating the predicted probability that a 50-year old develops CHD in the next ten years:

```{webr}
predict(logistic_model, newdata = data.frame(age = 50), type = "response")
```

Notice that we are specifying the data (x values) use for prediction using the same argument as in linear regression: we create a data frame with columns named identically to the actual data set used to fit the mode. We also must specify `type = "response"` to get probabilities. If you omit this argument, you will get a prediction on the log-odds scale, which isn't a probability!


## Inference for single regression coefficients

You have already seen that we can obtain Wald-based tests via the `summary()` command. To extract only that coefficient table, you can use the `tidy()` command from the broom package:

```{webr}
library(broom)
tidy(logistic_model)
```

To calculate Wald-based confidence intervals for each regression coefficient, we can use the `confint()` command, specifying the `level` argument:

```{webr}
tidy(logistic_model, conf.int = TRUE, conf.level = 0.9)
```


***

## Function quick reference

The following table summarizes the functions discussed above:

| Function | Purpose |
|----|-----------|
| `glm(formula, data, family = binomial)` | Fit a binary logistic regression model |
| `summary(model)` | View model summary and Wald tests |
| `predict(model, newdata, type = "response")` | Make predictions on the probability scale |
| `tidy(model, conf.int = TRUE, conf.level)` | Extract coefficient table with confidence intervals |



