---
title: "Binomial Logistic Regression"
subtitle: "An R Tutorial"
webr:
  packages:
    - broom
    - dplyr
    - ggformula
    - car
format: 
  live-html:
    toc: true
editor: source
editor_options: 
  chunk_output_type: console
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

In this tutorial we'll how to work with a binomial logistic regression mdel in R. To load the data for this tutorial, run the following code chunk:

```{r}
#| include: false
task <- 0
```


## Data overview

*Orobanche* is a genus of parasitic plants without chlorophyll that grow on the roots of flowering plants. In an experiment, seeds from two varieties, Orobanche aegyptiaca 75 and Orobanche aegyptiaca 73, where brushed with extract from either a cucumber root or a bean root. Researchers recorded the number of seeds that eventually germinated.

Run the code chunk below to load the data:
```{webr}
orobanche <- read.csv("https://aloy.github.io/stat230-materials/data/orobanche.csv")
```

The variables in the data set are:

- `y`: count of seeds germinated
- `n`: number of seeds
- `variety`: either oa75 or oa73
- `root`: either cucumber or bean


**Task `r (task <- task + 1)`.** Explain why this is an example of a binomial response as opposed to a binary response.


**Task `r (task <- task + 1)`.** Does there appear to be a relationship between the proportion of seeds that germinate and variety? What about root? To answer this, 

i. create boxplots of the estimated proportion by each variable.

ii. create boxplots of the estimated proportion using one variable on the x-axis and the other as the `fill` color.

What do you learn from these plots?




## Additive model

To begin, let's fit an additive logistic regression model where the main effects for `variety` and `root` are both included. Like in binary logistic regression, we use the `glm()` function to fit the model and specify `family = binomial`. The difference is in how we specify the response variable. For binomial logistics regression we specify the response as a proportion (e.g., `y/n`), and we need to use the `weights` argument to indicate the number of trials (i.e., `n`).


**Task `r (task <- task + 1)`.** Fill in the blanks in the below code chunk to fit the additive binomial logistic regression model:

```{webr}
oro_glm1 <- glm(___ ~ ___ + ___, data = orobanche, family = binomial, weights = ___)
```


**Task `r (task <- task + 1)`.** Report the fitted equation for the linear predictor (i.e., the log-odds of germination).

**Task `r (task <- task + 1)`.** Interpret the coefficient for `varietyoa75` in context.


**Task `r (task <- task + 1)`.** We can create plots of the Pearson or deviance residuals using the `residualPlots()` function from the `car` package and setting `type = "pearson"` or `type = "deviance"`. Create deviance residual plots for the fitted model. Do you see any model deficiencies?

```{webr}
# Put your residual plot code here
```


**Task `r (task <- task + 1)`.** Perform a deviance goodness-of-fit (GOF) test. What do you conclude?

:::{.callout-tip}
## Deviance goodness-of-fit test
The deviance GOF test statistic is given by the residual deviance of your fitted model. Then, calculate the upper-tail area under the chi-square distribution with degrees of freedom equal to the residual degrees of freedom:

```
1 - pchisq(stat, df)
```
:::

```{webr}
# Put deviance GOF code here
```


## Adding an interaction term

You should have found evidence of lack of fit, so we may be missing a term (especially sinc we don't see large outliers that would inflate the deviance GOF statistic). The only other thing we can add here is an interaction. The below code chunk updates our first model to include an interaction term.

```{webr}
oro_glm2 <- update(oro_glm1, . ~ . + variety:root)
```

:::{.callout-tip}
## Updating a model in R
You can use the `update()` function to modify an existing model. The syntax is `update(old_model, new_formula)`, where `new_formula` specifies the changes to the model formula. In this case, `. ~ . + variety:root` means "keep all existing terms and add the interaction between `variety` and `root`." (The `.` on the left side of the `~` represents the keeping the same response variable, and the `.` on the right side represents all of the existing predictors.)
:::

**Task `r (task <- task + 1)`.** Create deviance residual plots for the fitted model. Do you see any model deficiencies?


```{webr}
# Put your residual plot code here
```



**Task `r (task <- task + 1)`.** Perform a deviance goodness-of-fit test. What do you conclude?

```{webr}
# Put deviance GOF code here
```


***

## Function quick reference

The following table summarizes the functions discussed above:

| Function | Purpose |
|----|-----------|
| `glm()` | Fit generalized linear models, including binomial logistic regression models. |
| `update()` | Modify an existing model by adding or removing terms. |
| `residualPlots()` | Create residual plots to assess model fit. Set either `type = "pearson"` or `type = "deviance"` for binomial regression models. |
| `pchisq()` | Calculate cumulative probabilities for the chi-square distribution, useful for goodness-of-fit tests. |

